DROP TABLE IF EXISTS `tbl_group_chat`;
DROP TABLE IF EXISTS `tbl_group_member`;

CREATE TABLE tbl_group_chat (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE tbl_group_member (
    GROUP_ID INT,
    USER_ID INT,
    PRIMARY KEY (GROUP_ID, USER_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES TBL_GROUP_CHAT(ID),
    FOREIGN KEY (USER_ID) REFERENCES TBL_MEMBER(MEMBER_ID)
);